perform budnler install when all_the_repos
[#86467478]

diff --git a/bin/common b/bin/common
--- a/bin/common
+++ b/bin/common
@@ -66,6 +66,49 @@ function router_status() {
   done
 }
 
+##
+# Input: 
+#   package: The name of the installable package
+#   type: The installation source
+#   cmd: The command to execute once the package has been confirmed installed.
+#
+#   Note: the third argument, $cmd, is optional
+function which_p() { 
+  package="$1"; shift
+  type="$1"; shift
+  cmd="$@"
+
+
+  ##
+  # One of these will return 0 if the program is installed...
+  which "$cmd" 1>/dev/null 2>&1
+  errcodea=$?
+  type "$cmd" 1>/dev/null 2>&1
+  errcodeb=$?
+  # Meaning this will multiply to a result of 0
+  result=$(( $errcodea * $errcodeb ))
+
+  # Therefore, if result is zero, then it is already installed
+  if [[ $result -eq 0 ]] 
+  then
+    do_nothing=true
+  else
+    echo "Installing $package"
+    case $type in
+    "gem")
+      gem install "$package"
+      ;;
+    *)
+      echo "Error type: $type not defined"
+      exit 2
+      ;;
+    esac
+  fi
+
+  $cmd
+}
+export -f which_p
+
 function repo_all_the_way() {
   ORGREPO="$1"
   REPO="$(basename "${ORGREPO}")"
@@ -76,6 +119,29 @@ function repo_all_the_way() {
   else
     git submodule update --init --recursive
   fi
+
+  # Run bundler
+  which_p bundler gem bundle install
+
+  # If no ruby is specified, then we want to run bundler on the other installed rubies
+  if [[ -f .ruby-version ]]
+  then
+    donothing=true
+  else
+    which_p chruby exitout chruby
+
+    OLDRUBY=$(chruby | grep \*| awk '{print $2}')
+    for i in $(chruby | grep -v \*)
+    do
+      echo "Running bundler for ruby: $i"
+      chruby $i
+      which_p bundler gem bundle install
+    done
+    chruby $OLDRUBY
+  fi
+
+
+
   popd
 }
 export -f repo_all_the_way
